name: gig_saler_mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
   - assets/

  fonts:
    - family: DM_Mono
      fonts:
        - asset: assets/fonts/DM_Mono/DMMono-Italic.ttf
          style: italic
        - asset: assets/fonts/DM_Mono/DMMono-Light.ttf
        - asset: assets/fonts/DM_Mono/DMMono-LightItalic.ttf
          style: italic
        - asset: assets/fonts/DM_Mono/DMMono-Medium.ttf
        - asset: assets/fonts/DM_Mono/DMMono-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/DM_Mono/DMMono-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
        - asset: assets/fonts/Inter/Inter-Bold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter/Inter-Light.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter/Inter-Thin.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora/Lora-Bold.ttf
        - asset: assets/fonts/Lora/Lora-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Lora/Lora-Italic.ttf
          style: italic
        - asset: assets/fonts/Lora/Lora-Medium.ttf
        - asset: assets/fonts/Lora/Lora-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Lora/Lora-Regular.ttf
        - asset: assets/fonts/Lora/Lora-SemiBold.ttf
        - asset: assets/fonts/Lora/Lora-SemiBoldItalic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          style: italic


